#!/usr/bin/env bash
set -euo pipefail

required_vars=(
  PUBLIC_SUPABASE_URL
  PUBLIC_SUPABASE_PUBLISHABLE_KEY
  SUPABASE_SECRET_KEY
  PUBLIC_TURNSTILE_SITE_KEY
  TURNSTILE_SECRET_KEY
  RESEND_API_KEY
  RESELLER_PRICE_LIST_FROM
  RESELLER_ADMIN_EMAIL
  UPSTASH_REDIS_REST_URL
  UPSTASH_REDIS_REST_TOKEN
)

for variable in "${required_vars[@]}"; do
  if [[ -z "${!variable:-}" ]]; then
    echo "Missing required environment variable: ${variable}" >&2
    exit 1
  fi
done

cat > .env.staging <<EOF
PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLIC_SUPABASE_PUBLISHABLE_KEY}
SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
PUBLIC_TURNSTILE_SITE_KEY=${PUBLIC_TURNSTILE_SITE_KEY}
TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
RESEND_API_KEY=${RESEND_API_KEY}
RESELLER_PRICE_LIST_FROM=${RESELLER_PRICE_LIST_FROM}
RESELLER_ADMIN_EMAIL=${RESELLER_ADMIN_EMAIL}
UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}

PAGE_STATUS_ADMIN_DASHBOARD=ready
PAGE_STATUS_ADMIN_PRODUCTS=ready
PAGE_STATUS_ADMIN_CUSTOMERS=ready
PAGE_STATUS_ADMIN_AGENTS=ready
PAGE_STATUS_ADMIN_ORDERS=ready
PAGE_STATUS_ADMIN_INVOICES=ready
PAGE_STATUS_ADMIN_INQUIRIES=ready
PAGE_STATUS_ADMIN_RESELLER_APPLICATIONS=ready
PAGE_STATUS_ADMIN_ACTIVITY=ready
PAGE_STATUS_ADMIN_NOTIFICATIONS=ready
PAGE_STATUS_ADMIN_CONTENT=ready
PAGE_STATUS_ADMIN_SETTINGS=ready
PAGE_STATUS_AGENT_DASHBOARD=ready
PAGE_STATUS_AGENT_EARNINGS=ready
PAGE_STATUS_AGENT_CUSTOMERS=ready
PAGE_STATUS_AGENT_ORDERS=ready
PAGE_STATUS_AGENT_PAYMENTS=ready
PAGE_STATUS_AGENT_NOTIFICATIONS=ready
PAGE_STATUS_AGENT_SETTINGS=ready
EOF
