alter table "public"."agent_profile"
  add column if not exists "customer_id" "uuid";

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'agent_profile_customer_id_fkey'
      and conrelid = 'public.agent_profile'::regclass
  ) then
    alter table "public"."agent_profile"
      add constraint "agent_profile_customer_id_fkey"
      foreign key ("customer_id") references "public"."customer"("id") on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'agent_profile_customer_id_key'
      and conrelid = 'public.agent_profile'::regclass
  ) then
    alter table "public"."agent_profile"
      add constraint "agent_profile_customer_id_key" unique ("customer_id");
  end if;
end $$;

create index if not exists "agent_profile_customer_id_idx"
  on "public"."agent_profile" using "btree" ("customer_id");

create index if not exists "customer_phone_number_lookup_idx"
  on "public"."customer" using "btree" ("phone_number");

create index if not exists "customer_email_lower_lookup_idx"
  on "public"."customer" using "btree" (lower("email"))
  where "email" is not null;

create or replace function "private"."enforce_customer_unique_contact"() returns "trigger"
  language "plpgsql"
  security definer
  set "search_path" to ''
  as $$
begin
  if exists (
    select 1
    from public.customer
    where customer.id <> new.id
      and customer.phone_number = new.phone_number
  ) then
    raise exception 'Phone number already exists for another customer.';
  end if;

  if new.email is not null and exists (
    select 1
    from public.customer
    where customer.id <> new.id
      and lower(customer.email) = lower(new.email)
  ) then
    raise exception 'Email already exists for another customer.';
  end if;

  return new;
end;
$$;

alter function "private"."enforce_customer_unique_contact"() owner to "postgres";

drop trigger if exists "enforce_customer_unique_contact" on "public"."customer";
create trigger "enforce_customer_unique_contact"
  before insert or update of "phone_number", "email" on "public"."customer"
  for each row
  execute function "private"."enforce_customer_unique_contact"();

revoke all on function "private"."enforce_customer_unique_contact"() from public;

create table if not exists "public"."customer_registration_link" (
  "id" "uuid" default "extensions"."gen_random_uuid"() not null,
  "token" "text" not null,
  "token_hash" "text" not null,
  "expires_at" timestamp with time zone not null,
  "created_by" "uuid",
  "created_at" timestamp with time zone default "now"() not null,
  "revoked_at" timestamp with time zone,
  "revoked_by" "uuid",
  "use_count" integer default 0 not null,
  "last_used_at" timestamp with time zone,
  constraint "customer_registration_link_pkey" primary key ("id"),
  constraint "customer_registration_link_token_key" unique ("token"),
  constraint "customer_registration_link_token_hash_key" unique ("token_hash"),
  constraint "customer_registration_link_use_count_check" check ("use_count" >= 0)
);

alter table "public"."customer_registration_link" owner to "postgres";

comment on table "public"."customer_registration_link" is
  'Temporary customer registration links generated by admins for agent-assisted customer registration.';

create table if not exists "public"."customer_registration_link_agent" (
  "link_id" "uuid" not null,
  "agent_id" "uuid" not null,
  "notified_at" timestamp with time zone default "now"() not null,
  "read_at" timestamp with time zone,
  constraint "customer_registration_link_agent_pkey" primary key ("link_id", "agent_id")
);

alter table "public"."customer_registration_link_agent" owner to "postgres";

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_registration_link_created_by_fkey'
      and conrelid = 'public.customer_registration_link'::regclass
  ) then
    alter table "public"."customer_registration_link"
      add constraint "customer_registration_link_created_by_fkey"
      foreign key ("created_by") references "auth"."users"("id") on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_registration_link_revoked_by_fkey'
      and conrelid = 'public.customer_registration_link'::regclass
  ) then
    alter table "public"."customer_registration_link"
      add constraint "customer_registration_link_revoked_by_fkey"
      foreign key ("revoked_by") references "auth"."users"("id") on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_registration_link_agent_link_id_fkey'
      and conrelid = 'public.customer_registration_link_agent'::regclass
  ) then
    alter table "public"."customer_registration_link_agent"
      add constraint "customer_registration_link_agent_link_id_fkey"
      foreign key ("link_id") references "public"."customer_registration_link"("id") on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'customer_registration_link_agent_agent_id_fkey'
      and conrelid = 'public.customer_registration_link_agent'::regclass
  ) then
    alter table "public"."customer_registration_link_agent"
      add constraint "customer_registration_link_agent_agent_id_fkey"
      foreign key ("agent_id") references "public"."agent_profile"("id") on delete cascade;
  end if;
end $$;

create index if not exists "customer_registration_link_active_idx"
  on "public"."customer_registration_link" using "btree" ("expires_at", "created_at" desc)
  where "revoked_at" is null;

create index if not exists "customer_registration_link_agent_agent_id_idx"
  on "public"."customer_registration_link_agent" using "btree" ("agent_id", "notified_at" desc);

alter table "public"."customer_registration_link" enable row level security;
alter table "public"."customer_registration_link_agent" enable row level security;

drop policy if exists "Agents can read assigned registration links" on "public"."customer_registration_link";
create policy "Agents can read assigned registration links"
  on "public"."customer_registration_link"
  for select
  to "authenticated"
  using (
    exists (
      select 1
      from "public"."customer_registration_link_agent"
      where "customer_registration_link_agent"."link_id" = "customer_registration_link"."id"
        and "customer_registration_link_agent"."agent_id" = (select "private"."current_agent_profile_id"())
    )
  );

drop policy if exists "Agents can read own registration link notices" on "public"."customer_registration_link_agent";
create policy "Agents can read own registration link notices"
  on "public"."customer_registration_link_agent"
  for select
  to "authenticated"
  using ("agent_id" = (select "private"."current_agent_profile_id"()));

create or replace function "public"."list_admin_customer_rows"(
  "search_query" "text" default null,
  "customer_type_filter" "text" default null,
  "page_number" integer default 1,
  "page_size" integer default 10
) returns table("records" "jsonb", "total_rows" bigint)
  language "sql" stable
  security definer
  set "search_path" to ''
  as $$
  with normalized as (
    select
      nullif(lower(trim(search_query)), '') as search_value,
      nullif(customer_type_filter, '') as customer_type_value,
      greatest(page_number, 1) as safe_page_number,
      least(greatest(page_size, 1), 100) as safe_page_size
  ),
  base_rows as (
    select
      customer.id,
      customer.first_name,
      customer.last_name,
      customer.phone_number,
      customer.email,
      customer.address,
      customer.assigned_agent_id,
      customer.is_reseller,
      customer.created_at,
      customer.updated_at,
      agent_profile.display_name as assigned_agent_name,
      exists (
        select 1
        from public.agent_profile customer_agent
        where customer_agent.customer_id = customer.id
      ) as is_agent,
      lower(concat_ws(
        ' ',
        customer.first_name,
        customer.last_name,
        customer.phone_number,
        customer.email,
        customer.address,
        agent_profile.display_name
      )) as search_text
    from public.customer
    left join public.agent_profile
      on agent_profile.id = customer.assigned_agent_id
  ),
  filtered as (
    select base_rows.*
    from base_rows
    cross join normalized
    where (normalized.search_value is null or base_rows.search_text like '%' || normalized.search_value || '%')
      and (
        normalized.customer_type_value is null
        or (normalized.customer_type_value = 'reseller' and base_rows.is_reseller)
        or (normalized.customer_type_value = 'retail' and not base_rows.is_reseller)
      )
  ),
  counted as (
    select filtered.*, count(*) over () as total_rows
    from filtered
  ),
  paged as (
    select counted.*
    from counted
    cross join normalized
    order by counted.created_at desc, counted.id desc
    limit (select safe_page_size from normalized)
    offset (select (safe_page_number - 1) * safe_page_size from normalized)
  )
  select
    coalesce(
      jsonb_agg(to_jsonb(paged) - 'search_text' - 'total_rows' order by paged.created_at desc, paged.id desc),
      '[]'::jsonb
    ) as records,
    coalesce(max(paged.total_rows), (select count(*) from filtered), 0)::bigint as total_rows
  from paged;
$$;

alter function "public"."list_admin_customer_rows"("text", "text", integer, integer) owner to "postgres";

create or replace function "public"."apply_customer_payment_distribution"(
  "target_customer_id" "uuid",
  "payment_amount" numeric,
  "payment_method_value" "text",
  "payment_date_value" "date",
  "recorded_by_value" "uuid",
  "reference_number_value" "text" default null,
  "notes_value" "text" default null
) returns "jsonb"
  language "plpgsql"
  security definer
  set "search_path" to ''
  as $$
declare
  remaining_amount numeric := round(payment_amount, 2);
  total_balance numeric;
  order_row record;
  applied_amount numeric;
  distributions jsonb := '[]'::jsonb;
begin
  if remaining_amount <= 0 then
    raise exception 'Payment amount must be greater than zero.';
  end if;

  select round(coalesce(sum(public.compute_payment_balance(customer_order.id)), 0), 2)
  into total_balance
  from public.customer_order
  where customer_order.customer_id = target_customer_id
    and customer_order.order_status <> 'closed'
    and customer_order.payment_status in ('unpaid', 'partial');

  if total_balance <= 0 then
    raise exception 'This customer does not have unpaid pending order balances.';
  end if;

  if remaining_amount > total_balance then
    raise exception 'Payment amount exceeds the customer pending balance of %.', total_balance;
  end if;

  for order_row in
    select
      customer_order.id,
      public.compute_payment_balance(customer_order.id) as balance
    from public.customer_order
    where customer_order.customer_id = target_customer_id
      and customer_order.order_status <> 'closed'
      and customer_order.payment_status in ('unpaid', 'partial')
    order by customer_order.created_at asc, customer_order.id asc
    for update of customer_order
  loop
    exit when remaining_amount <= 0;
    continue when order_row.balance <= 0;

    applied_amount := least(remaining_amount, round(order_row.balance, 2));

    insert into public.payment (
      order_id,
      amount,
      payment_method,
      payment_date,
      recorded_by,
      reference_number,
      notes
    )
    values (
      order_row.id,
      applied_amount,
      payment_method_value,
      payment_date_value,
      recorded_by_value,
      nullif(reference_number_value, ''),
      nullif(notes_value, '')
    );

    distributions := distributions || jsonb_build_object(
      'order_id', order_row.id,
      'amount', applied_amount
    );

    remaining_amount := round(remaining_amount - applied_amount, 2);
  end loop;

  return jsonb_build_object(
    'applied_total', payment_amount,
    'distributions', distributions
  );
end;
$$;

alter function "public"."apply_customer_payment_distribution"("uuid", numeric, "text", "date", "uuid", "text", "text") owner to "postgres";

revoke all on function "public"."list_admin_customer_rows"("text", "text", integer, integer) from public;
revoke all on function "public"."list_admin_customer_rows"("text", "text", integer, integer) from anon;
revoke all on function "public"."list_admin_customer_rows"("text", "text", integer, integer) from authenticated;
grant execute on function "public"."list_admin_customer_rows"("text", "text", integer, integer) to service_role;

revoke all on function "public"."apply_customer_payment_distribution"("uuid", numeric, "text", "date", "uuid", "text", "text") from public;
revoke all on function "public"."apply_customer_payment_distribution"("uuid", numeric, "text", "date", "uuid", "text", "text") from anon;
revoke all on function "public"."apply_customer_payment_distribution"("uuid", numeric, "text", "date", "uuid", "text", "text") from authenticated;
grant execute on function "public"."apply_customer_payment_distribution"("uuid", numeric, "text", "date", "uuid", "text", "text") to service_role;

grant all on table "public"."customer_registration_link" to "service_role";
grant select on table "public"."customer_registration_link" to "authenticated";
grant all on table "public"."customer_registration_link_agent" to "service_role";
grant select on table "public"."customer_registration_link_agent" to "authenticated";

create or replace function "public"."list_admin_agent_rows"(
  "search_query" "text" default null,
  "status_filter" "text" default null,
  "page_number" integer default 1,
  "page_size" integer default 10
) returns table("records" "jsonb", "total_rows" bigint)
  language "sql" stable
  security definer
  set "search_path" to ''
  as $$
  with normalized as (
    select
      nullif(lower(trim(search_query)), '') as search_value,
      nullif(status_filter, '') as status_value,
      greatest(page_number, 1) as safe_page_number,
      least(greatest(page_size, 1), 100) as safe_page_size
  ),
  base_rows as (
    select
      agent_profile.id,
      agent_profile.user_id,
      agent_profile.customer_id,
      agent_profile.employee_id,
      agent_profile.first_name,
      agent_profile.last_name,
      agent_profile.display_name,
      agent_profile.status,
      auth_users.email,
      agent_profile.contact,
      agent_profile.created_at,
      agent_profile.updated_at,
      lower(concat_ws(
        ' ',
        agent_profile.employee_id,
        agent_profile.first_name,
        agent_profile.last_name,
        agent_profile.display_name,
        auth_users.email,
        agent_profile.contact,
        agent_profile.status
      )) as search_text
    from public.agent_profile
    left join auth.users as auth_users
      on auth_users.id = agent_profile.user_id
  ),
  filtered as (
    select base_rows.*
    from base_rows
    cross join normalized
    where (normalized.search_value is null or base_rows.search_text like '%' || normalized.search_value || '%')
      and (normalized.status_value is null or base_rows.status = normalized.status_value)
  ),
  counted as (
    select filtered.*, count(*) over () as total_rows
    from filtered
  ),
  paged as (
    select counted.*
    from counted
    cross join normalized
    order by counted.last_name asc, counted.first_name asc, counted.id asc
    limit (select safe_page_size from normalized)
    offset (select (safe_page_number - 1) * safe_page_size from normalized)
  )
  select
    coalesce(
      jsonb_agg(to_jsonb(paged) - 'search_text' - 'total_rows' order by paged.last_name asc, paged.first_name asc, paged.id asc),
      '[]'::jsonb
    ) as records,
    coalesce(max(paged.total_rows), (select count(*) from filtered), 0)::bigint as total_rows
  from paged;
$$;

alter function "public"."list_admin_agent_rows"("text", "text", integer, integer) owner to "postgres";

revoke all on function "public"."list_admin_agent_rows"("text", "text", integer, integer) from public;
revoke all on function "public"."list_admin_agent_rows"("text", "text", integer, integer) from anon;
revoke all on function "public"."list_admin_agent_rows"("text", "text", integer, integer) from authenticated;
grant execute on function "public"."list_admin_agent_rows"("text", "text", integer, integer) to service_role;
